### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by chrisschaub** [phonegap-build/StatusBarPlugin#4] opened 2013-11-08 16:58 UTC
If we set StatusBar.hide() and launch the app landscape mode, a long about 200px wide bar runs along the right side of the screen. If we launch in portrait, no problem. Only on IOS7, of course.

**Comment by bostondv** [comment] 2013-11-08 21:16
I'm getting this as well, though I call the following onDeviceReady:

```
window.StatusBar.overlaysWebView(true);
window.StatusBar.styleLightContent();
```

**Comment by bau720123** [comment] 2013-11-25 15:15
I have the same problem on iOS7，any solution?
I use iPad mini

**Comment by CrazyEraserUK** [comment] 2013-12-10 13:17
I'm also seeing the same issue.

**Comment by bau720123** [comment] 2013-12-10 13:55
I found another problem in Landscape mode
when in Landscape mode with StatusBarPlugin，your page can't be Slide up and down anymore，It will be completely stationary

to solve this problem have two way
one，remove this plugin and rebuilt and reopen your app and everything changes normal
two，it must change to portrait mode first and change back to Landscape mode，that the page can Slide up and down rightly

**Comment by bau720123** [comment] 2013-12-15 16:53
any suggestions?

**Comment by DevdudeSami** [comment] 2013-12-22 14:56
Any suggestions guys? It can't be that it's either landscape mode or the StatusBar plugin... Both are crucial to apps.

**Comment by yannkozon** [comment] 2014-01-15 13:46
I have the same problem on iOS7, ipad air, iphone5.
Any suggestions ?

**Comment by tbassett44** [comment] 2014-01-16 19:18
I am having the same issue - only with iPad in landscape mode on startup and only with StatusBar plugin installed

**Comment by bau720123** [comment] 2014-01-20 13:42
so sad...
no one can solve the problem
Who is the original developer?
I want to ask for help

**Comment by orenagiv** [comment] 2014-01-26 10:31
I'm getting a 3/4 screen BLACK when launching the App on iPad 2 (iOS7) in LANDSCAPE mode.

I starts fine - but once a 'change background color' command is triggered - the screen becomes 3/4 black, and the status-bar remains the same color.
I'm referring to these commands:
StatusBar.backgroundColorByHexString('#000000');
Or
StatusBar.backgroundColorByName('black');

If I trigger the StatusBar.hide() command - then I get the 1/4 screen WHITE - just as described in the thread above.

If I launch the App when the device is in PORTRAIT mode - the above bugs do NOT occur, and everything is okay.
It only happens when the device is in LANDSCAPE.

**Comment by tbassett44** [comment] 2014-01-26 17:30
I ended up deciding not to use the statusbar plugin because of this issue.  I ended up just making the app fullscreen in ios 7 and adjusting the HTML to allow me to make a "statusbar" whatever color I needed.  This worked for me because I only needed the lightstyle for the text in the menubar, i didnt need to change that once the app started.  So I just set the .plist key-value "Status bar style"=>"UIStatusBarStyleLightContent".

**Comment by tuxslayer** [comment] 2014-02-04 17:13
A small hint on what is wrong :) http://stackoverflow.com/questions/2664980/uiscreen-applicationframe-returning-incorrect-rectangle-on-landscape-application

Something like this was working for me: https://dl.dropboxusercontent.com/u/7265609/landscape.patch
It doesn't respect doubled ("in-call") status bar but otherwise looks good.

**Comment by FedericoRoffiNektan** [comment] 2014-02-05 10:23
Hi, I have the same problem on iOS7 but I can't test @tuxslayer 's patch on my pc, I can only use PhoneGap Build.

**Comment by escheffers** [comment] 2014-02-18 14:14
With the patch from @tuxslayer we still have some problems. The show and hide method stil use [[UIScreen mainScreen] bounds].
However changing them to [self.webView.superview bounds] as well gives a distorted view as well.
I haven't found a fully working solution as of for now. :(

**Comment by xcash** [comment] 2014-02-20 13:05
:+1:  here. the problem is still present using Phonegap Build 3.3.0.
Starting the app in landscape leaves a white vertical band on the right.

Please fix this or this plugin is useless.

**Comment by wildabeast** [comment] 2014-02-25 21:27
Try out version 1.1.0 on PhoneGap Build -- should fix this.

**Comment by bau720123** [comment] 2014-02-26 05:04
I Try out version 1.1.0 on PhoneGap Build，problem was fixed
Thanks @wildabeast

**Comment by wildabeast** [comment] 2014-02-26 18:23
Fixed in 1.1.0, closing.

**Closed as completed by wildabeast** 2014-02-26 18:23 UTC

**Comment by rolbr** [comment] 2014-02-27 08:21
@wildabeast 
I'd like to confirm this fix. Thank you soooo much!

**Comment by orenagiv** [comment] 2014-02-27 10:04
I can also confirm it works perfectly now.

P.S.
Not directly related to the issue here - but please note that in PGB 3.3 if you have the Viewport meta-tag with "height=device-height" - then landscape orientation is all screwed up.
If you remove the "height=device-height" - then it all works well, but has some side effects (such as input-fields not always get focused when the keyboard is opened).

**Comment by jieves** [comment] 2014-02-27 15:27
I confirm. Problem solved.
Thank you very much !
