### ISSUE TITLE
If you Show and Hide the StatusBar - it will expand the screen-size by ~20 pixels

### ISSUE THREAD

**Issue by orenagiv** [phonegap-build/StatusBarPlugin#21] opened 2014-02-25 22:17 UTC
If you show the status-bar and the hide it - the screen size increases in around 20 pixels in width and height.
If you show and hide it again - it will increase in another 20 pixels.

**Comment by wildabeast** [comment] 2014-02-25 22:19
@orenagiv A quick test and I couldn't reproduce. Are you on PhoneGap Build, and if so can you share your app ID?

**Comment by orenagiv** [comment] 2014-02-25 23:00
I'm building through PGB.
Unfortunately I cannot share that App with you at this time.

I'm not sure if it matters - but I'm using the config.xml to update the info.plist:

```
    <gap:plugin name="com.phonegap.plugin.statusbar" />

    <gap:config-file platform="ios" parent="UIViewControllerBasedStatusBarAppearance">
        <false />
    </gap:config-file>
    <gap:config-file platform="ios" parent="UIStatusBarHidden">
        <true />
    </gap:config-file>
```

**Comment by orenagiv** [comment] 2014-02-25 23:30
Correction: It only resizes the screen by height (not by width).
Everytime - by exactly 20 pixels in height.

I use the PGB Debugger and simply do:
StatusBar.show();
StatusBar.hide();
Right after the .hide() - the $(window) size shows a 20px increase in height:

![screen shot 2014-02-26 at 1 29 17 am](https://f.cloud.github.com/assets/2144775/2264621/bb830abe-9e74-11e3-8d4e-5ec24514dcb7.png)

**Comment by wildabeast** [comment] 2014-02-26 02:06
Should be fixed now -- please verify.

**Comment by orenagiv** [comment] 2014-02-26 07:14
Works!!!

**Comment by wildabeast** [comment] 2014-02-26 07:26
Great, closing.

**Closed as completed by wildabeast** 2014-02-26 07:26 UTC
